// Code generated by "stringer -type=itemType"; DO NOT EDIT.

package aoc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[itemMul-0]
	_ = x[itemDo-1]
	_ = x[itemDont-2]
}

const _itemType_name = "itemMulitemDoitemDont"

var _itemType_index = [...]uint8{0, 7, 13, 21}

func (i itemType) String() string {
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return "itemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
